SuperHouse/esp-open-rtos

include/espressif/esp_system.h

sdk_system_get_vdd() was added by mistake in #104

Removed sdk_system_get_vdd()

---

examples/ws2812_rainbow/Makefile
examples/ws2812_rainbow/ws2812_rainbow.c
extras/ws2812/component.mk
extras/ws2812/ws2812.c
extras/ws2812/ws2812.h

Now we have a »NeoPixel« support!
The demo displays a fancy animated rainbow generated on-the-fly.

WS2812B driver & example

---

core/esp_spi.c
core/include/esp/spi.h
core/include/esp/spi_regs.h

Supports both SPI buses, frequency up to 80MHz, etc.

Hardware SPI driver

---

core/esp_spi.c
core/include/esp/spi.h

Bugfix and some new functionality:
static const spi_settings_t my_settings = {
.mode = SPI_MODE0,
.freq_divider = SPI_FREQ_DIV_4M,
.msb = true,
.endianness = SPI_LITTLE_ENDIAN,
.minimal_pins = true
};
....
spi_settings_t old;
spi_get_settings(1, &old); // save current settings
spi_set_settings(1, &my_settings);
// work with spi here
....
spi_set_settings(1, &old); // restore saved settings

SPI big endian swap bug fix, spi_get_settings()/spi_set_settings()

---

examples/ds18b20_broadcaster/ds18b20_broadcaster.c
examples/ds18b20_onewire/ds18b20_onewire.c
extras/ds18b20/ds18b20.c
extras/ds18b20/ds18b20.h
extras/onewire/onewire.c
extras/onewire/onewire.h

The original DS18B20 API was functional, but not ideal for working with multiple sensors on the same bus.  In addition to a bunch of misc cleanup (use of open-drain mode, removing unnecessary critical sections, etc), this update adds several new API functions for identifying and accessing DS18B20 devices in more flexible (and much faster!) ways.

DS18B20 API Improvements

---

examples/dht_sensor/Makefile
examples/dht_sensor/dht_sensor.c
extras/dht/component.mk
extras/dht/dht.c
extras/dht/dht.h

Just getting my feet wet with the ESP8266 and the FreeRTOS code you all have been building.  Thanks for all the work and please feel free to critique what I've done here.
~Jonathan

Added DHT library to extras and sample code to examples

---

extras/sntp/sntp.c

sntp: free the pbuf after sending the request

---

examples/dht_sensor/dht_sensor.c
extras/dht/dht.c
extras/dht/dht.h

Fixed DHT library.
Tested with DHT11 and DHT22 modules.

DHT11/DHT22 sensor library fixed.

---

extras/spiffs/spiffs_config.h

In spiffs 0.3.6, it is recommended to enable the temporal fd cache feature. This optimizes the opening of frequently opened files. The cost is 6 extra bytes per file descriptor.

spiffs: enable temporal cache for spiffs v 0.3.6

---

core/app_main.c
core/include/esp/types.h
core/include/sysparam.h
core/sysparam.c
examples/sysparam_editor/Makefile
examples/sysparam_editor/sysparam_editor.c

As @foogod is restricted on time I got his permission to create a PR for his excellent sysparam framework. I have rebased his branch, squashed his commits and added licensing information as well as fixed a few compiler warnings.

Sysparam by @foogod

---

core/sysparam.c

This synchronizes writers, but not yet readers.
It appears the code supports multiple readers and a single writer. There seems to be an issue with multiple compaction still to be explored, but this PR is start to at least synchronize the writers.

sysparam: add a semaphore to synchronize writers.

---

examples/sysparam_editor/sysparam_editor.c

Helpful to be able to disable echo when sending commands fast, so that the editor can consume them faster than they arrive. This adds and 'echo' command to toggle echo on and off.

sysparam editor: add an echo command.

---

core/esp_gpio.c
core/include/esp/gpio.h

Need this to blink the LED on nodemcu boards! Was discussed here https://github.com/SuperHouse/esp-open-rtos/issues/60 Have not integrated this with the other gpio functions to avoid a performance regression, and if desired then perhaps that could be a separate PR.

GPIO16 support.

---

examples/ds1307/Makefile
examples/ds1307/main.c
extras/ds1307/component.mk
extras/ds1307/ds1307.c
extras/ds1307/ds1307.h

Driver for the most common RTC DS1307.

DS1307 RTC driver + example

---

examples/ultrasonic/Makefile
examples/ultrasonic/main.c
extras/ultrasonic/component.mk
extras/ultrasonic/ultrasonic.c
extras/ultrasonic/ultrasonic.h

Driver for ultrasonic range meters like HC-SR04, HY-SRF05 and so on.

Driver for ultrasonic range meters + example

---

examples/hmc5883l/Makefile
examples/hmc5883l/main.c
extras/hmc5883l/component.mk
extras/hmc5883l/hmc5883l.c
extras/hmc5883l/hmc5883l.h

HMC5883L is most common 3-axis digital compass IC.

HMC5883L driver + example

---

extras/spiffs/mkspiffs/.gitignore

mkspiffs binaries added to .gitignore.

Add mkspiffs binary to .gitignore

---

extras/ds18b20/component.mk
extras/ds18b20/ds18b20.c

1. Added support for DS18S20 (DS1820)
2. Bus scan fixed: now it searches only DS18x20

DS18x20 dirver fix

---

extras/dhcpserver/dhcpserver.c

initialize dhcpserver_task_handle = NULL
corrert error printf "OTA TFTP" to "DHCP Server Error"

dhcpserver.c corrections.

---

examples/ds1307/main.c
extras/ds1307/ds1307.c
extras/ds3231/ds3231.c

AM/PM mode hours reading, zero based month

RTC drivers fix

---

examples/ds1302_test/Makefile
examples/ds1302_test/main.c
extras/ds1302/component.mk
extras/ds1302/ds1302.c
extras/ds1302/ds1302.h

Driver for yet another widely spread RTC

DS1302 RTC driver + example

---

examples/wifi_scan/Makefile
examples/wifi_scan/main.c

WiFi scan example

---

core/app_main.c
open_esplibs/libmain/user_interface.c

Otherwise a restart ends up in a wdt halt. This change improves things.
Also comment the point at which the bus clock that drives the uart changes on startup and comment out the change in the uart divisor. This at least allows a consistent uart baud rate during a restart if using the rate 115200. When restarting the bus clock does not change and the rom resets the rate to 115200 so if using a rate of 115200 the rate is consistent and the startup messages can be see without corruption.

Flush the uart tx fifo before a restart.

---

extras/bmp280/bmp280.c
extras/bmp280/bmp280.h

Add skip option and possibility to select oversampling for temperature with bmp/bme280  (see datasheet)

Bmp280 option

---

.gitmodules
extras/http-parser/component.mk

> This is a parser for HTTP messages written in C. It parses both requests and responses. The parser is designed to be used in performance HTTP applications. It does not make any syscalls nor allocations, it does not buffer data, it can be interrupted at anytime. Depending on your architecture, it only requires about 40 bytes of data per message stream (in a web server that is per connection).
> Features:
> - No dependencies
> - Handles persistent streams (keep-alive).
> - Decodes chunked encoding.
> - Upgrade support
> - Defends against buffer overflow attacks.
Good base for HTTP client and server.

HTTP parser intergation

---

extras/ds18b20/ds18b20.c

Fix for https://github.com/SuperHouse/esp-open-rtos/issues/294

ds18b20 fix for temperature below zero

---

core/include/stdout_redirect.h
core/newlib_syscalls.c
extras/spiffs/esp_spiffs.c

It is required for working console output redirect.
Should fix #300.

Allow changing write function of stdout

---

core/app_main.c
core/debug_dumps.c
extras/i2s_dma/i2s_dma.c
extras/ssd1306/ssd1306.c
open_esplibs/libmain/user_interface.c
open_esplibs/libwpa/wpa_main.c

I got some errors when build with esphttpd

add some missing include & fixed display output on sh1104

---

extras/spiffs/mkspiffs/mkspiffs.c

Process recursive folder
```
+files
+--folder1
|   \---file1.txt
|   \---file2.txt
\--file3.txt
```
to spiffs filename:
```
+ folder1/file1.txt
+ folder1/file2.txt
+ file3.txt
```

Process recursive folder for spiffs images

---

.gitmodules
examples/crc_example/Makefile
examples/crc_example/crc_config_perso.h
examples/crc_example/crc_main.c
extras/crc_generic/component.mk

Hi, i have finish the first release of my crc library based on many things found about CRC ( details in my repository). I post it as submodule because the code can be ported for other things. 
- This library can compute crc from 1 to 64 bit.
- Every parameters of crc is present. (Poly,Init,RefIn,RefOut,XorOut )
- Independent crc struct for multiple usage.
- You can select algorithm you want use (4 at this moment. Thank to Sven Reifegerste original lib)
- Sized functions ( 8bits, 16 bits, 32bits and 64 bits) for save RAM usage if needed.
- Pre-generated  constant lookup table for many crc standard 
- Can generate  lookup table  for polynom multiple of 8bits ( 8,16,24,32,..)
It is the first release. Maybe some bugs are present for custom crc. Some code optimisation can be done too.  Someone …

CRC library

---

examples/bh1750/Makefile
examples/bh1750/bh1750_example.c
extras/bh1750/bh1750.c
extras/bh1750/bh1750.h
extras/bh1750/component.mk
extras/pwm/pwm.c
extras/pwm/pwm.h

Hi, this is a "preliminary" driver pull request - so that others know the driver already exist and they don't have to rewrite it (though it's trivial).
Since I did change extras/i2c lib a bit, and there's pull request #321 in the queue for similar functionality (but cleaner), I'll rebase this once #321 is merged - basically the commit 0b1197b can be dropped.

bh1750 i2c light sensor driver + pwm cleanup

---

examples/upnp/Makefile
examples/upnp/README.md
examples/upnp/httpd.c
examples/upnp/httpd.h
examples/upnp/lwipopts.h
examples/upnp/upnp.c
examples/upnp/upnp.h
examples/upnp/upnp_test.c

I would like to share an example to create Upnp server. In this example I emulate a WeMo switch plug (wifi switch) recognizable by Amazon echo dot. It was not really easy to find a way to use a udp multicast, until I found a great example https://github.com/kanflo/uhej-example

Upnp example emulating a Wemo switch

---

extras/ssd1306/ssd1306.c

SPI3 protocol with SSD1306 work now  ( test done)

Fix SPI3 protocol with SSD1306

---

examples/pcf8591/main.c
extras/pcf8591/pcf8591.c
extras/pcf8591/pcf8591.h

- Added support for configuring analog inputs
- Added support for DAC output

PCF8591 driver update

---

examples/ds3231_test/ds3231_test.c
extras/bmp180/bmp180.c
extras/bmp280/README.md
extras/i2c/i2c.c
extras/i2c/i2c.h
extras/sht3x/README.md

Configurable I2C clock stretching

---

examples/bme680/README.md
examples/bme680/bme680_heating_profiles/Makefile
examples/bme680/bme680_heating_profiles/bme680_heating_profiles.c
examples/bme680/bme680_one_sensor/Makefile
examples/bme680/bme680_one_sensor/bme680_one_sensor.c
examples/bme680/bme680_two_sensors/Makefile
examples/bme680/bme680_two_sensors/bme680_two_sensors.c
extras/bme680/README.md
extras/bme680/bme680.c
extras/bme680/bme680.h
extras/bme680/bme680_types.h
extras/bme680/component.mk

I have written a driver for the brand new Bosch Sensortec BME680. BME680 is an ulta-low-power environmental sensor that integrates temperature, pressure, humidity and gas sensors in only one unit.
Please add it to the master branch.

Driver for Bosch Sensortec BME680 added

---

examples/esphttpd/user_main.c

Seeing stack overflows on this one.

esphttpd: increase stack size for task wsbcast

---

examples/ccs811/README.md
examples/ccs811/ccs811_one_sensor/ccs811_one_sensor.c
examples/ccs811/ccs811_plus_sht3x/ccs811_plus_sht3x.c
examples/ccs811/ccs811_temperature/ccs811_temperature.c
extras/ccs811/README.md
extras/ccs811/ccs811.c
extras/ccs811/ccs811.h
extras/ccs811/ccs811_platform.h
extras/ccs811/component.mk

- small corrections
- changes to make it possible to use the same driver source code also with ESP32 (ESP-IDF)

CCS811 driver updates

---

examples/bme680/README.md
examples/bme680/bme680_heating_profiles/bme680_heating_profiles.c
examples/bme680/bme680_one_sensor/bme680_one_sensor.c
examples/bme680/bme680_two_sensors/bme680_two_sensors.c
extras/bme680/README.md
extras/bme680/bme680.c
extras/bme680/bme680.h
extras/bme680/bme680_platform.h
extras/bme680/bme680_types.h
extras/bme680/component.mk

- minor changes
- changes to make it possible to use the same driver and example source code also with ESP32 (ESP-IDF)

BME680 driver updates

---

examples/sysparam_editor/sysparam_editor.c

Missed some more places needing stdout flushing.

sysparam editor: more stdout flushing.

---

examples/sht3x/sht3x.c
extras/sht3x/README.md

- error message added in case the sensor initialization failed
- additional notein README.md

Minor changes in SHT3x driver

---

extras/ws2812_i2s/ws2812_i2s.c
extras/ws2812_i2s/ws2812_i2s.h

Prevent multiple initialization memory allocation and inform user if allocation has fail.

ws2812 fix possible memory leak

---

extras/sdio/sdio.c

This patch fixes the problem, while receiving `R1b` type of response from the card.
In case of `R1b` response the continuous stream that the card sends must be checked whether the signal indicates busy status and wait until a non zero response.

Fix SDIO send_command

---

FreeRTOS/Source/include/FreeRTOS.h
FreeRTOS/Source/stream_buffer.c
FreeRTOS/Source/tasks.c

FreeRTOS: update to svn r2541.

---

extras/stdin_uart_interrupt/stdin_uart_interrupt.c

Rewrite to have the IRQ handler read the character and place it in a FreeRTOS queue.
Was seeing odd RX errors with the prior driver, an occasional old character inserted. It only affected one particular device so might have been timing critical. Could not spot the problem, but toggling the interrupt enable outside the interrupt handler looked like trouble, so rewrote this to avoid that. This proposed rewrite reads the character from the fifo within the interrupt handler, and uses a FreeRTOS queue to queue them, and it also enables some RX error checking (parity, framing, breaks) and simple counters for these.

stdin_uart: rewrite to use a FreeRTOS queue.

---

extras/mbedtls/component.mk
extras/mbedtls/net_lwip.c

Tried to sync net_lwip.c with the upstream version and integrate fixes.

mbedtls: update and integrate upstream fixes.

---

core/esp_iomux.c

Reverts SuperHouse/esp-open-rtos#671

Revert "Shrink gpio<>iomux maps"

---

extras/sdio/component.mk
extras/sdio/sdio.c

Fix for #666 (nice number, isn't it?)

CMD25 workaround for SDIO

---

core/include/esp/spi.h

Not even sure if anyone cares :smiley: I, for instance, have not seen a device that uses LSB bit ordering, but... for the sake of completeness and what if...
Something I noticed when I was "playing" with different transfer modes. To show what it is I wrote a small test program:
```c
enum { LSB, MSB };
enum { USING_CS, MINIMAL_PINS };
// -----8<----->8------
spi_init(1, SPI_MODE0, SPI_GET_FREQ_DIV(2000,40), LSB, SPI_LITTLE_ENDIAN, USING_CS);
for (;;) {
switch (getchar()) {
case 'c': {
spi_set_command(1,4,0xC);
spi_set_dummy_bits(1,4,false);
spi_transfer_8(1, 0x6a);
spi_clear_dummy(1);
spi_clear_command(1);
break;
}
case 'a': {
spi_set_address(1,4,0xA);
spi_set_dummy_bits(1,4,false);
spi_transfer_8(1, 0x6a);
spi_clear_dummy(1);
spi_clear_address(1);
break;
}
}
```
Current implementation …

Fixed command and address in LSB mode

---

extras/dht/dht.c
extras/dht/dht.h

Fix for #719.
New sensor type in `dht` component

Support for Itead Si7021

---

extras/ssd1306/ssd1306.c

- it is based on https://github.com/mcauser/Adafruit_SSD1306/commit/7a748d2e52114571c229900094460657a781bc67

Added support for OLED with size 64x48

---

extras/ssd1306/ssd1306.c

Here's an optimized version with a lot less overhead.

optimize ssd1306_draw_vline

---

extras/ssd1306/ssd1306.c

Here's an optimized version with a lot less overhead.

optimize ssd1306_fill_rectangle

---

extras/fonts/data/font_roboto_10pt.h
extras/fonts/data/font_roboto_8pt.h

The font_info_t fields were messed up.

fix ssd1306 roboto fonts
