SuperHouse/esp-open-rtos

- common.mk
Before switching to esp-open-rtos I spent a great deal of time scratching my head until I found out about the ESP ROM SPI flash erase bug when my program failed to boot. As the esptool fix has not been pulled yet, the flashing order needs to change.
> Changed flashing order

- core/esp_gpio_interrupts.c
- core/esp_timer.c
- core/include/common_macros.h
- core/include/esp/dport_regs.h
- core/include/esp/gpio.h
- core/include/esp/gpio_regs.h
- core/include/esp/iomux.h
- core/include/esp/iomux_regs.h
- core/include/esp/registers.h
- core/include/esp/timer.h
- core/include/esp/timer_private.h
- core/include/esp/timer_regs.h
- core/include/esp/types.h
- core/include/esp/wdt_regs.h
- examples/blink/blink.c
- examples/blink_timers/blink_timers.c
- examples/button/button.c
- examples/experiments/timers/timers.c
As discussed in Issue #8, this change moves to a parameterized-macro and struct-based approach to defining MMIO access registers.  It also renames a number of structs and bit constants (and a couple of related typedefs) to use more consistent naming, etc.
I also went ahead and broke registers.h out into individual .h files for each peripheral type (registers.h now just #includes all the individual *_regs.h files)
> Convert headers to new *_regs.h format

- core/include/esp/dport_regs.h
- core/include/esp/registers.h
- core/include/esp/rtcmem_regs.h
- core/include/esp/spi_regs.h
- core/include/esp/uart_regs.h
(Re: issue #8)
Fleshing out a bunch more of the register headers:  Added *_regs.h files for UART, SPI, and RTC memory regions.  Also adding a bunch more register info to dport_regs.h based on info from http://esp8266-re.foogod.com/wiki/Memory_Map#dport0
> Add more *_regs.h definitions

- core/include/common_macros.h
- core/include/esp/dport_regs.h
- core/include/esp/gpio_regs.h
- core/include/esp/iomux_regs.h
- core/include/esp/spi_regs.h
- core/include/esp/timer_regs.h
- core/include/esp/uart_regs.h
- core/include/esp/wdt_regs.h
Per my comment on issue #8, `__attribute__ (( packed ))` can apparently cause GCC to do strange things with accesses under `-O0`, so this removes them (they shouldn't really be necessary anyway).
This also includes a patch to the VAL2FIELD / SET_FIELD macros to remove an AND operation which is probably rarely needed and makes them slightly less efficient than they need to be in general (I added VAL2FIELD_M / SET_FIELD_M which have the old behavior in case anything down the line actually does need it).
> Remove packed attribute from register structs

- core/include/esp/uart_regs.h
Looks like I had a rather grievous cut/paste error in my previous uart_regs.h submission..
> Fix broken UART(i) definition

- ld/eagle.app.v6.ld
(Re: Issue #35)
Segments tagged with .irom or .irom0 should always be linked into the irom region, whether they're part of the sdklib or not..
> Fix linker script handling of irom/irom0 segments

- examples/bmp180_i2c/Makefile
- examples/bmp180_i2c/README.md
- examples/bmp180_i2c/bmp180_i2c.c
- extras/README.md
- extras/bmp180/LICENSE
- extras/bmp180/README.md
- extras/bmp180/bmp180.c
- extras/bmp180/bmp180.h
- extras/bmp180/component.mk
- extras/i2c/LICENSE
- extras/i2c/README.md
- extras/i2c/component.mk
- extras/i2c/i2c.c
- extras/i2c/i2c.h
Hi,
I've written a more "advanced" example I wanted to share with the public, it also contains a driver for the BMP180/BMP085 digital pressure sensor, which can be used as an example how to use external devices and distribute data between tasks.
Let me know if this is okay with you (License, reference to external I2C lib etc.)
I'm not sure if it makes more sense to create an external repository for the BMP180 driver (Like the one for the I2C driver) and link it also into the example, but this would lead to an even more polluted .gitmodules file.
Regards
Angus71
> Added bmp180_i2c example

- examples/pwm_test/Makefile
- examples/pwm_test/pwm_test.c
- extras/pwm/component.mk
- extras/pwm/pwm.c
- extras/pwm/pwm.h
This pull request merges #72 and #73 plus the following changes:
1. Handle duty cycle 0% so it does not crash
2. Handle duty cycle 100% so output remains constant on
3. Add license notices
4. Modify test code to cover 0% and 100% duty cycle.
Compiled and tested on adafruit's Huzza esp8266 board.  Requires an LED or an oscilloscope to verify that the test code works as intended.
> Initial PWM implementation from gpascualg

- core/esp_gpio.c
- core/include/esp/gpio.h
- core/include/esp/iomux.h
- core/include/esp/types.h
Created `gpio_set_pullup` to configure pullups independently of direction.
Removed GPIO_INPUT_PULLUP direction type.
Added misc other helper functions in iomux.h
> Separate pullup config out of `gpio_enable()`

- include/espressif/esp_sta.h
I'm certain this was an oversight... This is a needed change for the cgiwifi stuff in esphttpd.
> fix sdk_bss_info STAILQ_ENTRY

- extras/ds18b20/ds18b20.c
There is a bug in the driver for DS18B20: instead of delaying for 750**ms** it waits only for 750**us**, which obviously causes that read temprature is not valid (it's default 85 degrees).
> Fix delays in DS18B20 driver

- core/include/esp/gpio.h
Same as afd58bc1ffb1aa9cf2f030d05d7491906925c3e6
> esp/gpio.h c++ linker compatibility

- .travis.yml
- common.mk
- include/ssid_config.h
Previous behavior was all warnings were treated as errors.  This is now
controllable via a make variable and defaults to off (but can be turned on in
local.mk for those who still want the old behavior)
> Add WARNINGS_AS_ERRORS make flag

- .travis.yml
- core/app_main.c
- utils/travis_build/install_esptool2.sh
- utils/travis_build/install_toolchain.sh
This is similar to #126 - git history was rewritten on a submodule of esp-open-sdk (esp-lwip this time) so historical commits on esp-open-sdk no longer check out cleanly, and our Travis builds broke.
Failure seems to be compounded by the 4MB log limit in Travis - toolchain plus all examples build with V=1 can blow the 4MB limit, so there's a commit here to only build V=1 on a failing example.
Long-term we may need to find a different way to include a toolchain in Travis, as the way we're using esp-open-sdk (including a historical commit) doesn't seem like it's sustainable.
> Fix Travis toolchain build (again)

- core/app_main.c
- core/esp_phy.c
- core/include/esp/gpio.h
- core/include/esp/gpio_regs.h
- core/include/esp/phy.h
- core/include/sdk_internal.h
- core/phy_info.c
- include/espressif/phy_info.h
I've started digging into the PHY management, both in the SDK and a bit at the hardware register.
These two commits have what I've figured out so far - including an esp-open-rtos implementation for configuration the default SDK PHY settings.
> PHY management features

- ld/common.ld
This may not be ready for merging yet, but I wanted to put it up for discussion/review anyhow.
Moves most .rodata to flash by default. http_get_mbedtls example's RAM footprint shrinks by 5317 bytes (7284 byte .rodata -> 1967 byte.) blink example shrinks by 3981 bytes (5948 to 1967).
Most usefully, you can do things like compile in debug message strings without taking a RAM hit for them.
Fundamentally there's not a lot in this change, it draws on the code we've had in e-o-r for a while to do unaligned reads from flash. The main difference was testing various types of operation and watching for unwanted/risky accesses that might happen when the flash caching layer was disabled.
I'm not keen to merge yet because of potential performance implications. The GNU linker doesn't seem to place …
> Store .rodata in flash by default

- examples/mqtt_client/mqtt_client.c
I noticed I could not reconnect to my RasPi MQTT server following a disconnect. Adding DisconnectNetwork(...) did the trick.
> Call DisconnectNetwork(...) before MQTT reconnect

- core/app_main.c
This should have been done ages ago as part of #3, it's my fault I overlooked it. Without this PR, rand() produces a very predictable series of numbers after reset.
The only place I know that it's used by default is for the WPA Key Nonce, which is currently identical following each reset. This does not have any bearing on TLS - mbedTLS uses its own entropy engine, which is tied directly to the hardware random number generator.
A better long term fix would be to make `srand()` a no-op and have `rand()` return `hwrand()` each time its called, but newlib doesn't provide an easy mechanism (that I can see, anyhow) to replace `rand()`. So sticking with this for now.
If you're relying on `rand()` heavily in your own code, suggest having a task regularly call `srand(hwrand() ^ rand());` in order …
> Seed libc PRNG from hardware RNG on reset

- extras/paho_mqtt_c/MQTTClient.c
- extras/paho_mqtt_c/MQTTClient.h
Try resolve issue #152 
When a MQTT packet is being received but the packet length is larger than allocated buffer or reading timeout occurs, ignore that packet and reinitialize broker connection.
Caller have to pay attention to buffer size and timeout value in NewMQTTClient call. But at least ESP will not crash if timeout or receiving buffer overflow.
Also modified sending buffer length calculation bug.
I still don't like the way how Paho handles error. Seeking improvement in the future.
> Handling MQTT read failure and send buffer length

- extras/i2c/i2c.c
The code appeared to be forcing the outputs high rather than using an open drain to let them float high and this attempts to correct this.
Initialize the pins when the driver is initialized.
Enable the internal pull-ups to prevent them floating too high if not connected and damaging the circuit.
> i2c: use open drain outputs.

- examples/bmp280/Makefile
- examples/bmp280/bmp280_example.c
- extras/bmp280/README.md
- extras/bmp280/bmp280.c
- extras/bmp280/bmp280.h
- extras/bmp280/component.mk
BMP280 is a successor of BMP180 pressure sensor. But it has different communication protocol. It has different registers and different operation modes.
At first I thought about extending existing BMP180 driver but there would have been two many preprocessor conditions or run-time branching.
So, here's my implementation of BMP280 driver.
I tested it with my BMP280 module. The output data is the same as with ArduinoUNO + BMP280.
> BMP280 pressure sensor driver and example.

- examples/bmp180_i2c/bmp180_i2c.c
- extras/bmp180/bmp180.c
- extras/bmp180/bmp180.h
An application using multiple I2C devices will need it's own
loop. This reworks the code to make the detection, calibration
constant loading, and measurment functions available too without
having to use the bmp810 task which is still retained.
Adds support for oversampling.
Fixes a bug in the calculation of the temperature.
Better error handling. Checks for I2C errors and errors in the loading
of the calibration constants and propagates these up.
> bmp180: make a lower level interface available and support oversampling.

- examples/spiffs/Makefile
- examples/spiffs/spiffs_example.c
- extras/spiffs/README.md
- extras/spiffs/component.mk
- extras/spiffs/esp_spiffs.c
- extras/spiffs/esp_spiffs.h
- extras/spiffs/mkspiffs/Makefile
- extras/spiffs/mkspiffs/README.md
- extras/spiffs/mkspiffs/mkspiffs.c
- extras/spiffs/spiffs_config.h
In [PR#163](https://github.com/SuperHouse/esp-open-rtos/pull/163) was suggested to have ability to select how SPIFFS is configured, as a singleton during compile-time or during run-time. This PR adds this feature.
By default SPIFFS is configured as before at compile-time. If run-time configuration is needed `SPIFFS_SINGLETON=0` should be specified in program's Makefile. In that case `esp_spiffs_init` accepts two arguments: address and size of spiffs flash region.
Logical page size, block size and erase block size is still a compile time defined parameters. I don't see a use case when those parameters needs to be changed in run-time. If needed they can be redefined in program's Makefile as well.
> SPIFFS: Selectable configuration of SPIFFS

- core/include/common_macros.h
- core/include/esp/iomux.h
- examples/i2s_audio/Makefile
- examples/i2s_audio/i2s_audio_example.c
- examples/ws2812_i2s/Makefile
- examples/ws2812_i2s/ws2812_i2s_colour_loop.c
- extras/i2s_dma/README.md
- extras/i2s_dma/component.mk
- extras/i2s_dma/i2s_dma.c
- extras/i2s_dma/i2s_dma.h
- extras/ws2812_i2s/README.md
- extras/ws2812_i2s/component.mk
- extras/ws2812_i2s/ws2812_i2s.c
- extras/ws2812_i2s/ws2812_i2s.h
This PR includes:
* Wrapper library *i2s_dma* that encapsulates i2s + dma initialization. 
* *ws2812_i2s* driver. It uses *i2s_dma* library to control strip of WS2812 leds.
* *ws2812_i2s* example. It demonstrates usage of *ws2812_i2s* driver.
* *i2s_audio* example. It demonstrates usage of *i2s_dma* library to output sound using I2S DAC chip.
There's a [video](https://www.youtube.com/watch?v=OTSbcgWY39A) of ws2812_i2s example.
> i2s_dma wrapper, ws2812_i2s driver and examples.

- core/esp_spi.c
- core/include/esp/gpio.h
- core/include/esp/iomux.h
- core/include/esp/iomux_regs.h
The allows the IOMUX_GPIO<n>_FUNC_<function> definitions to be used here which seems to be the result of discussions in https://github.com/SuperHouse/esp-open-rtos/pull/171
> iomux_set_function: remove the IOMUX_FUNC transform of the func argument

- include/etstimer.h
- open_esplibs/libmain/user_interface.c
Fix for https://github.com/SuperHouse/esp-open-rtos/issues/176.
The problem was  that *sdk_os_timer_* timers use FreeRTOS timers underneath which do not pass a timer argument to the callback function. They pass FreeRTOS timer handle which should be used in function **pvTimerGetTimerID** to extract the actual argument.
*sdk_ets_timer_* timers do not use FreeRTOS timers and pass a timer argument directly into a callback function.
> Fix for system_deep_sleep ignoring argument

- examples/bmp280/bmp280_example.c
- extras/bmp280/README.md
- extras/bmp280/bmp280.c
- extras/bmp280/bmp280.h
The BME280 is close to compatible with the existing BMP280 and extends it with support for measuring humidity, so support has been bundled into the bmp280 driver.
The example now auto-detects the device and displays the humidity for the BME280.
The I2C bus initialization has been moved out of the bmp280 driver to support multiple devices.
The check-id and reset logic has been bundled into the driver initialization. It needs to be re-initialized after reset anyway and the chip-id is need to initialize it, just re-initialize to reset.
Support has been added for multiple devices. The calibration data storage needs to be managed by the caller rather than static data. The caller can choose the I2C address to allow two BMx280 devices to be used on the same I2C bus.
An interface has been added …
> BME280 support.

- open_esplibs/libmain/user_interface.c
Could see system_uart_de_swap define in the header file but not in libmain, but added it anyway.
> libmain: add sdk_system_uart_swap and sdk_system_uart_de_swap

- core/include/esp/interrupts.h
40002a58     $a3 = rtc_intr_handler
40002a5e     $a4 = 0x0
40002a60     $a2 = 0x3
40002a62     call ets_isr_attach
> esp/interrupts.h: Add RTC interrupt number.

- extras/i2c/i2c.c
Using gpio_enable and flipping the configuration appears to be a major cause of poor performance in the i2c driver, so this changes to using the outputs as open-drain only.
> i2c: use open drain for output rather than flipping between input and output.

- core/include/esp/gpio_regs.h
Specifically, in the high 16 bits of GPIO.IN register.
> esp/gpio_regs.h: Add info about strapping pins captured in GPIO.IN register.

- include/espressif/esp_sta.h
See mention in some other esp code that if the bssid_set value is not zero then the bssid must be set. Should the examples be initializing this to zero explicitly?
> Comment the sdk_station_config slots.

- core/include/sysparam.h
- core/sysparam.c
Rename the get/set_int api functions to get/set_int32.
Add get/set_int8 api functions too in anticipation of more efficient implementations for these.
> sysparams: get/set int32 and int8 apis.

- core/exception_vectors.S
- core/include/debug_dumps.h
This commit adds initial support for <a href="/resetnow/esp-gdbstub">esp-gdbstub</a> (which is based on Espressif implementation and adapted to esp-open-rtos). 
A thing I'd like to hear an opinion on: two global symbols were added: `debug_exception_handler` and `debug_saved_ctx`. I'll take any suggestion regarding renaming them to suit some existing namespace.
Implementation notes:
1. Default debug exception vector now calls the address stored in `debug_exception_handler`. It's `fatal_exception_handler` by default, and gdbstub changes it during initialization.
2. `debug_saved_ctx` is used to save a0 — a4 at the start of debug vector. Also, it stores a0 — a1 in the interrupt vector (the rest of registers is saved later on the stack). The latter allows to use Ctrl-C in GDB.
> core: exception_vectors: initial esp-gdbstub support

- examples/aws_iot/aws_iot.c
- examples/mqtt_client/mqtt_client.c
- extras/paho_mqtt_c/MQTTClient.c
- extras/paho_mqtt_c/MQTTClient.h
- extras/paho_mqtt_c/MQTTConnect.h
- extras/paho_mqtt_c/MQTTConnectClient.c
- extras/paho_mqtt_c/MQTTDeserializePublish.c
- extras/paho_mqtt_c/MQTTESP8266.c
- extras/paho_mqtt_c/MQTTESP8266.h
- extras/paho_mqtt_c/MQTTFormat.h
- extras/paho_mqtt_c/MQTTPacket.c
- extras/paho_mqtt_c/MQTTPacket.h
- extras/paho_mqtt_c/MQTTPublish.h
- extras/paho_mqtt_c/MQTTSerializePublish.c
- extras/paho_mqtt_c/MQTTSubscribe.h
- extras/paho_mqtt_c/MQTTSubscribeClient.c
- extras/paho_mqtt_c/MQTTUnsubscribe.h
- extras/paho_mqtt_c/MQTTUnsubscribeClient.c
``` 
$ nm -g build/paho_mqtt_c.a | grep " T "
00000068 T mqtt_packet_decode
000000f4 T mqtt_packet_decode_buf
0000002c T mqtt_packet_encode
0000027c T mqtt_packet_equals
000000c4 T mqtt_packet_len
000002d4 T mqtt_packet_read
00000330 T mqtt_packet_readnb
00000120 T mqtt_read_char
0000010c T mqtt_read_int
00000208 T mqtt_read_str_len
00000254 T mqtt_strlen
00000130 T mqtt_write_char
00000180 T mqtt_write_cstr
00000144 T mqtt_write_int
000001c4 T mqtt_write_mqqt_str
000000f8 T mqtt_serialize_ack
00000170 T mqtt_serialize_puback
000001a4 T mqtt_serialize_pubcomp
0000001c T mqtt_serialize_publish
00000188 T mqtt_serialize_pubrel
00000420 T mqtt_client_new
000004cc T mqtt_connect
00000840 T mqtt_disconnect
00000730 T mqtt_publish
00000590 T mqtt_subscribe
00000688 T mqtt_unsubscribe
00000468 T …
```
> paho_mqtt_c: refactor: rename symbols so they all have same prefix

- open_esplibs/libmain/timers.c
Fixes https://github.com/SuperHouse/esp-open-rtos/issues/140 and probably lots of other issues.
> timers: esp library timer callbacks expect their argument not a xTimerHandle

- core/include/esp/phy_regs.h
I plan to implement some of libphy functions in C later, so I thought it would be good to have an attempt of phy registers description.
Also, if somebody is interested in doing something similar, radare2 has recently been updated with better xtensa support — I posted a message <a href="https://groups.google.com/forum/#!topic/esp8266-re/cSWvEex6hpI">here</a>.
> core: add phy regs definition

- examples/tsl2561/Makefile
- examples/tsl2561/tsl2561_example.c
- extras/tsl2561/component.mk
- extras/tsl2561/tsl2561.c
- extras/tsl2561/tsl2561.h
This pull request adds support for the [TSL2561 Light Sensor](https://cdn-shop.adafruit.com/datasheets/TSL2561.pdf)
It uses the I2C module from the `extras` directory of this project.
This driver supports setting an integration time from the presets of (13ms, 101ms, and 402ms), as well as a 1X and 16X gain. The driver uses `vTaskDelay` when the lux value is requested from the sensor so it has time to integrate the sensors and get a reading. The sensor remains in a "powered down" mode when not in use.
Interrupts and custom integration times are not supported in this PR.
> Add a TSL2561 driver and example usage

- extras/bmp180/bmp180.h
- extras/bmp280/bmp280.h
- extras/dhcpserver/include/dhcpserver.h
- extras/dht/dht.h
- extras/ds18b20/ds18b20.h
- extras/ds3231/ds3231.h
- extras/i2c/i2c.h
- extras/i2s_dma/i2s_dma.h
- extras/onewire/onewire.h
- extras/pwm/pwm.h
- extras/ws2812/ws2812.h
- extras/ws2812_i2s/ws2812_i2s.h
Basically "extern "C" was added to some of the extras headers.
> Make headers in extras more cpp friendly

- common.mk
- core/newlib_syscalls.c
- extras/spiffs/esp_spiffs.c
- extras/stdin_uart_interrupt/component.mk
- extras/stdin_uart_interrupt/stdin_uart_interrupt.c
- parameters.mk
Fix for https://github.com/SuperHouse/esp-open-rtos/issues/248
In this PR function `_read_r` makes additional call to `_read_stdin_r`.
So, **stdin_uart_interrupt** can override only part that it is interested in.
Also **spiffs** overrides `_read_r`, handles file descriptors and leave stdin to `_read_stdin_r` whoever overrides it.
> Fix spiff and stdin_uart_interrupt overiding the same read function

- .travis.yml
- README.md
- include/.gitignore
- include/ssid_config.h
This patch moves the private SSID config to a file not included in the git repo. The current setup is a real foot gun for developer. Non-developers can almost as easily create a separate file as editing the ssid_config.h file. Alternatively a template file could be included. When developers are dealing with many git repo copies and trying to test things, it's just too much of a burden to have to manually config git for the ssid_config.h file, and we need to commit to the master branch and test that so can not deal with this in a local branch. As a developer, don't expect more contributions from me here if this is not fixed.
> Use a separate file for the private SSID config.

- FreeRTOS/Source/portable/esp8266/portmacro.h
- core/app_main.c
- core/include/sdk_internal.h
- open_esplibs/include/esplibs/libmain.h
- open_esplibs/include/esplibs/libnet80211.h
- open_esplibs/include/esplibs/libphy.h
- open_esplibs/include/esplibs/libpp.h
- open_esplibs/include/esplibs/libwpa.h
- open_esplibs/libmain/user_interface.c
This update adds some new sdk internal structures and updates the existing ones. The global definitions have been moved into the include/esplibs/ directory and sorted per library and per source object file. These are needed to support sdk code to be submitted and if this could be landed first then it would help split them up and might avoid some merge ordering problems. If this were to move a slot then it might break the code, but it's a small part of what it is to be submitted and some extra checks have been added to the structure layouts to try to detect edit problems.  Checks have also been added for the lwip netif slots offsets known to be used by the sdk binary code which should help other people using esp-open-rtos as a lwip development platform.
> Update and re-organise the sdk internal definitions.

- include/espressif/esp_system.h
- open_esplibs/libmain/user_interface.c
- wifi_set_sleep_type returns a bool success flag.
- wifi_get_sleep_type seemed useless, just returning an argument. Added an implementation using sdk_pm_get_sleep_type.
> wifi_get/set_sleep_type: add source code implementations plus fixes.

- open_esplibs/libmain/user_interface.c
Add source code for functions touching the struct netif to better support lwip development: sdk_wifi_get_ip_info, sdk_wifi_set_ip_info, sdk_wifi_get_macaddr, sdk_wifi_set_macaddr.
Also code for sdk_wifi_station_get_connect_status.
> open_esplibs user_interface: source code for functions touching the struct netif.

- open_esplibs/libnet80211/ieee80211_sta.c
The function sdk_wifi_station_start is one of two paths that allocates a lwip struct netif and also accesses the netif->hwaddr slot so this is required for lwip development.
Also code for sdk_wifi_station_stop and sdk_sta_status_set to better understand the status state.
> open_esplibs libnet80211: source code for sdk_wifi_station_start and stop.

- examples/mcp4725_test/Makefile
- examples/mcp4725_test/main.c
- extras/mcp4725/component.mk
- extras/mcp4725/mcp4725.c
- extras/mcp4725/mcp4725.h
The MCP4725 is a low-power, high accuracy, single channel, 12-bit buffered voltage output Digital-to-Ana-
log Convertor (DAC) with non-volatile memory (EEPROM). Its on-board precision output amplifier allows it to achieve rail-to-rail analog output swing.
> Driver + example for MCP4725 12-bit I2C DAC

- open_esplibs/libnet80211/wl_cnx.c
Also code for sdk_cnx_sta_leave, although disabled due to accessing static date, but it shows a reference to the netif->flags and the NETIF_FLAG_DHCP flag removed in lwip v2.
> open_esplibs libnet80211: source code for sdk_cnx_node_search.

- core/include/sysparam.h
- core/sysparam.c
- examples/sysparam_editor/sysparam_editor.c
Useful after editing parameters to get best read performance. Also to clear out the history, such as old passwords, but would take two calls for that.
> sysparam: export the 'compact' function, added it to the editor.

- core/esp_spi.c
- core/include/esp/spi.h
- examples/spi_test/Makefile
- examples/spi_test/spi_test.c
Hello, i wrote some new functions to spi. Inspired from multiple spi drivers i had like this one : https://github.com/MetalPhreak/ESP8266_SPI_Driver.
New funtions:
```
spi_set_command(uint8_t bus,uint8_t bits, uint16_t data);
spi_set_address(uint8_t bus,uint8_t bits, uint32_t data);
spi_set_dummy_bits(uint8_t bus, uint8_t bits, bool pos);
spi_clear_address(uint8_t bus);
spi_clear_command(uint8_t bus);
spi_clear_dummy(uint8_t bus);
void spi_repeat_send_8(uint8_t bus, uint8_t data, int32_t repeats);
void spi_repeat_send_16(uint8_t bus, uint16_t data, int32_t repeats);
void spi_repeat_send_32(uint8_t bus, uint32_t data, int32_t repeats);
```
I tested these functions on the oscilloscope. all work fine but you can do some test to check. 
I had some strange behavior with memcpy so i used this …
> Spi features

- examples/ads1115_test/Makefile
- examples/ads1115_test/main.c
- extras/ads111x/ads111x.c
- extras/ads111x/ads111x.h
- extras/ads111x/component.mk
> The ADS1113, ADS1114, and ADS1115 are precision analog-to-digital converters (ADCs) with 16 bits of resolution offered in an ultra-small, leadless QFN-10 package or an MSOP-10 package.
Unfortunately I overvoltaged my ADS1115 during tests, so I hope someone can help me with testing.
> ADS1113/ADS1114/ADS1115 I2C ADC driver + example

- open_esplibs/libmain/user_interface.c
Fix sdk_system_rtc_mem_write and sdk_system_rtc_mem_read,
the functions did not use the user-provided offsets to rtc_mem.
Without using offset, rboot's rtcdata access, and its
temp_rom handling were broken.
> Fix ignored offset in rtc_mem access.

- core/esp_spi.c
- core/include/esp/spi.h
Hi i discovered 2 bug with the new SPI API, one is fixed. I still think the way for resolve the second.
First Bug:
Wrong address was set, just swap instructions order to solve it.
Second Bug:
It is a special case that the API does not take into account.
If CS is software , If Address/command/dummy is set and if data transfered is greater than SPI_BUFFER, it will send a second time (or more) addr/dummy/cmd as data :(.
I have some idea to solve it.
1 - If addr/dummy/cmd set, limit transfert to BUF SIZE  ( not sure if it is a good idea )
2 - add extras instructions to clear and  rearm dummy/addr/cmd.
But maybe an other way to solve it is better, some suggestion ?
> Fixes SPI Bug(s)

- examples/pca9685_pwm/Makefile
- examples/pca9685_pwm/main.c
- extras/pca9685/component.mk
- extras/pca9685/pca9685.c
- extras/pca9685/pca9685.h
> The PCA9685 is an I2C-bus controlled 16-channel LED controller optimized for Red/Green/Blue/Amber (RGBA) color backlighting applications. Each LED output has its own 12-bit resolution (4096 steps) fixed frequency individual PWM controller that operates at a programmable frequency from a typical of 24 Hz to 1526 Hz with a duty cycle that is adjustable from 0 % to 100 % to allow the LED to be set to a specific brightness value. All outputs are set to the same PWM frequency.
> Driver for PCA9685 + example

- extras/httpd/httpd.c
- extras/httpd/httpd.h
- extras/httpd/readme.txt
I wanted to merge yesterday, but was a bit late.
Changes:
- support for WebSocket frames >125 bytes
- fixed minor issue with timeout
- updated readme
I'm not planning any major changes so it's safe to merge.
> httpd: support for large WebSocket frames

- include/espressif/esp_system.h
- open_esplibs/libmain/user_interface.c
I started playing with multicast and following [this tread](http://lwip.100.n7.nabble.com/Multicast-Example-td10415.html) I realized the `netif` struct needed to be exported from user_interface.c. There was a static function `_get_netif` that I exported as `sdk_system_get_netif` (to follow the naming standard of user_interface.c) . A function prototype is available in esp_system.h.
> Added sdk_system_get_netif

- extras/sntp/sntp.c
The function sntp_set_servers() duplicates the strings supplied in the
server_url[] array into new strings but forgets to allocate the extra
byte needed for the \0 terminator for each string.
Fix the problem by using strdup(), which allocates the right amount of
memory and copies the string at once.
---
I also wonder why it's allocating heap space instead of just copying the pointers, which seems more efficient to me.
> extras/sntp: fix an off-by-one bug in sntp_set_servers()

- core/app_main.c
- examples/tick_idle_hooks/FreeRTOSConfig.h
- examples/tick_idle_hooks/Makefile
- examples/tick_idle_hooks/hooks_example.c
Sometimes it's nice to have access to the FreeRTOS tick and idle hooks. This pull request enables that by allowing user code to override the default implementations provided in `app_main.c`.
To use this, include a file in your project called `FreeRTOSConfig.h` with (at least) the contents shown in the example. You may need to `make clean` to cause FreeRTOS to be rebuilt. Overrides for `vApplicationIdleHook` and `vApplicationTickHook` can now be provided.
**One Caveat** with this pull request specifically is that I do not yet fully understand the sleep functions provided in the SDK. I believe that if `WIFI_SLEEP_LIGHT` is passed in the idle hook, the wifi radio will sleep if connected (or the call will fail if not connected). Either way, the call is noisy and that makes timing and whether …
> Give FreeRTOS Hooks weak linkage

- core/app_main.c
- core/debug_dumps.c
- extras/ads111x/ads111x.c
- extras/bmp180/bmp180.c
- extras/bmp280/bmp280.c
- extras/ds1307/ds1307.c
- extras/ds1307/ds1307.h
- extras/ds3231/ds3231.c
- extras/ds3231/ds3231.h
- extras/hmc5883l/hmc5883l.c
- extras/i2c/i2c.c
- extras/i2c/i2c.h
- extras/i2s_dma/i2s_dma.c
- extras/ina3221/ina3221.c
- extras/ina3221/ina3221.h
- extras/mcp4725/mcp4725.c
- extras/ms561101ba03/ms561101ba03.c
- extras/pca9685/pca9685.c
- extras/pcf8574/pcf8574.c
- extras/ssd1306/ssd1306.c
- extras/ssd1306/ssd1306.h
- extras/tsl2561/tsl2561.c
- open_esplibs/libmain/user_interface.c
- open_esplibs/libwpa/wpa_main.c
Hi, i do some work on i2c.
Currently done:
Add custom delay to get true 400kHz at 160Mhz and  320KHz at 80Mhz ( cant be faster with 80 MHz for now )
Add status flag check ( usefull when more than one task use i2c ) ( Level 1 API dont start if bus busy) 
Rewrote comment (Update them)
Rework printf debug
My plans (need opinion):
-Selectable frequency. (100kHz / 400kHz )
-Add force option. ( if bus busy, stop com and start a new one  for level1 API)
-Add possibility to write and read 16 bit data.
-Change data from `i2c_slave_read(uint8_t slave_addr, uint8_t data, uint8_t *buf, uint32_t len)` to a data pointer. Function dont send register address when NULL. 
-Optional (if time permit): Add multiple i2c setting support.
What is better: 
Add new functions to include 16 bits possibility or add …
> I2c optimization and features

- examples/tsl4531/Makefile
- examples/tsl4531/tsl4531_example.c
- extras/tsl2561/tsl2561.c
- extras/tsl4531/component.mk
- extras/tsl4531/tsl4531.c
- extras/tsl4531/tsl4531.h
Hey I'm back again with another light sensor driver, this time the TSL4531.
[TSL4531 Light Sensor](https://media.digikey.com/pdf/Data%20Sheets/Austriamicrosystems%20PDFs/TSL4531.pdf)
It uses the I2C module from the `extras` directory of this project.
This driver supports setting an integration time from the presets of (100ms, 200ms, and 400ms), as well as a "skip power save" mode which just comes straight from the data sheet. I played around with the "skip power save" mode a bit but didn't see any noticeable differences. Perhaps it draws less current but I'm not sure at the moment.
The driver uses `vTaskDelay` when the lux value is requested from the sensor so it has time to integrate the sensors and get a reading. The sensor remains in a "powered down" mode when not in use.
The cool …
> Add a TSL4531 driver and example

- core/esp_spi.c
Seems it's OK to use memcpy() for unaligned read or aligned write to the register area, but we need a special method for unaligned writes.
See #352.
> Fixes unaligned writes to SPI data register

- examples/http_server/fsdata/fs/about.html
The URL on non gnu.org was changed as @Alge pointed out in in #381.
> Fix for #381

- extras/mdnsresponder/mdnsresponder.c
Priority #1 appears not to be working. Priority #2 works just fine.
> Change xTaskCreate priority.

- .travis.yml
Seeing odd build failures in lwip v2 with the old version of the tools chain used for travis, but it builds fine locally with more recent versions so give that a try.
> travis: update the esp-open-sdk version used.

- extras/paho_mqtt_c/MQTTClient.c
On MQTTClient.c function mqtt_subscribe, if more than MQTT_MAX_MESSAGE_HANDLERS are registered, the variable rc receives the value of grantedQoS.
If grantedQoS = 0, and all handlers are already occupied, it goes on and returns 0 to the caller.
> MQTT ignores too many handlers registered

- extras/paho_mqtt_c/MQTTESP8266.c
Some timing functions of the ESP82668's MQTT client port seems to be using incorrect values. That was causing tasks to busy wait for a packet inside the cycle function, increasing power usage and not letting lower priority tasks execute.
> Mqtt timer not sleeping

- examples/aws_iot/ssl_connection.h
- examples/http_get_mbedtls/http_get_mbedtls.c
- examples/tls_server/tls_server.c
- extras/mbedtls/include/mbedtls/config.h
- extras/mbedtls/net_lwip.c
This is the latest stable version, so perhaps we should consider updating to this.
> Update mbed TLS to 2.5.1

- examples/ad770x/Makefile
- examples/ad770x/main.c
- extras/ad770x/ad770x.c
- extras/ad770x/ad770x.h
- extras/ad770x/component.mk
Basic driver for AD7705/AD7706 (TM7705/7706) - 3 V/5 V, 1 mW, 2-/3-Channel, 16-Bit, Sigma-Delta ADCs with 3-wire serial interface.
> Driver for AD7705/AD7706 SPI ADC

- core/esp_hwrand.c
- lib/allsymbols.rename
The fiq NMI calls rand() from lmac:lmac.a:sdk_lmacTxFrame and the NMI must not touch the newlib reent structure or enter critical regions etc, so just use the simple and safe hwrand implementation as a
substitute.
> Use hwrand for the sdk uses of rand, in particular with the NMI.

- extras/i2c/i2c.h
Looks like this was test wip code that should not have been included. Want to be able to set the i2c per-project rather than having to patch the driver.
@Zaltora What do you think about this change?
Did not check if some examples depended on a higher speed?
> i2c: remove wip 400k define

- extras/httpd/httpd.h
Add a missing `typedef` to the `httpd.h` header. Before, the header would define a _variable_ `WS_MODE` which caused linking errors when the header was included in multiple translation units. Now `WS_MODE` is a type alias which was the original intent according to my best understanding.
> httpd: add missing typedef

- .travis.yml
This is a quick fix for Travis build.
Travis upgraded their default build environment to ubuntu trusty which for some reason broke installation of pyserial.
> Fix pyserial import on travis CI

- core/debug_dumps.c
- core/include/user_exception.h
If the software crashes, it is essential in some applications like robotics to e.g. shut down motors for safety. This PR adds an API for the user to add their own exception handler.
> Add a hook for a user defined exception handler

- examples/terminal/terminal.c
As the terminal example was meant to echo characters typed I added fflush since the line buffering policy has changed.
While on the topic, should we make IRQ driven stdin standard (which would fix #454)?
> Added fflush for examples/terminal echo

- core/newlib_syscalls.c
- examples/http_get/http_get.c
- examples/http_get_bearssl/http_get_bearssl.c
- examples/tls_server_bearssl/tls_server_bearssl.c
- extras/mbedtls/net_lwip.c
- extras/paho_mqtt_c/MQTTESP8266.c
- extras/spiffs/esp_spiffs.c
- extras/spiffs/spiffs_config.h
- extras/wificfg/wificfg.c
- lwip/include/arch/cc.h
- lwip/include/lwipopts.h
This patch gets the newlib standard stream descriptors playing well with the lwip socket descriptors and the spiffs file descriptors. The LWIP_SOCKET_OFFSET is now defined to be 3, rather than zero, to avoid clashing with the standard stream descriptors, and the SPIFFS_FILEHDL_OFFSET is bumped up to start after the lwip descriptors.
**This is not yet ready to merge.** I need to seek help from upstream lwip on the error that was disabled to allow this to build, why LWIP_SOCKET_OFFSET can not be used with an external FD_SET. A quick inspection did not find many problems, so I am probably missing something. But perhaps this will allow progress and more testing and feedback.
See also https://github.com/SuperHouse/esp-open-rtos/issues/445
> lwip: define LWIP_POSIX_SOCKETS_IO_NAMES as zero

- extras/wificfg/wificfg.c
* Correct checking of the AP password and SSID lengths.
* Only enable AP mode if it is really configured enabled.
* Only start the http server if wifi is enabled.
These are the fixes from https://github.com/SuperHouse/esp-open-rtos/pull/459 that I would adopt, thank you to @kanflo
> wificfg: correct a few initialization issues

- core/newlib_syscalls.c
When I pass a multi-line string to printf, only the first line is printed after PR #437 .
This fixes it.
> Fix a printf issue.

- extras/ssd1306/ssd1306.h
Simple fix.  Discovered while working on a project and thought others would find it useful.
> Fix a typo in ssd1306 driver that prevents compiling with c++ compiler

- examples/ws2812_i2s/ws2812_i2s_colour_loop.c
- extras/ws2812_i2s/ws2812_i2s.h
- Add a way to set color with one variable, "RGB888" standard.
I discovered a bug or a problem with current i2s library.
When you do 2 update without delay, second update don't work.
```
ws2812_i2s_update(pixels, PIXEL_RGB);
ws2812_i2s_update(pixels, PIXEL_RGB);
```
Was thinking that this line : `while (i2s_dma_processing) {}; ` will prevent this but not.
It is work when i add this:
`sdk_os_delay_us(260 + 30 * (dma_buffer_size / type)); `
I can fix with a system that control the minimum time in us and return error is we cant update. (sdk api) but i wondering if i2s lib dont set flag correctly ? any clue ?
> color and timing (ws2812_i2s)

- extras/spiffs/esp_spiffs.c
The commit ebdd2f9 defined some offsets to differentiate between the
standard, socket and file descriptors.
SPIFFS_FILEHDL_OFFSET was updated accordingly but the code didn't use
that constant and this broke the SPIFFS POSIX API.
Fix it by initializing the fh_ix_offset field of the spiffs_config
structure to SPIFFS_FILEHDL_OFFSET.
> Fix the SPIFFS POSIX API (#489)

- extras/i2c/i2c.c
The i2c_stop should not be there.
We have to keep the bus started and then issue again the i2c_start in order for the function to handle correctly the repeated-start.
> Fixed Repeated-start in I2C

- extras/sntp/sntp.c
- extras/sntp/sntp_fun.c
Changed quote marks with triangle brackets
for sntp.h to allow user creating a custom sntp.h
> Allow overrides of sntp.h

- extras/i2c/i2c.c
- extras/i2c/i2c.h
In an effort to make the I2C driver operate faster, I noticed a few optimization opportunities in the code. This code goes over 1 MHz at 160 MHz clock speed and I suppose ~800 kHz would be achievable with 80 MHz clock speed.
After the refactoring to multiple coexisting I2C bus instances, the code was making a lot of lookups in the `i2c_bus_descriptor` structure during the transaction. Especially in `i2c_delay()`, that caused quite a bit of overhead. Therefore the delay is now looked up only once in `i2c_start()`.
Furthermore, I noticed that in some occasions `gcc`with `-O2` was optimizing `i2c_delay()` aggressively. Namely, the counter wasn't even assigned on every inline occurrence of `i2c_delay()` in the code. This resulted in an infinite loop due to the counter wrapping over. The …
> I2C optimization

- examples/wificfg/Makefile
- examples/wificfg/wificfg.c
- extras/wificfg/content/wificfg/sta.html
- extras/wificfg/wificfg.c
* When IPv6 is enabled the http server and the captive portal DNS now also accept IPv6 connections. The interface and peer IPv6 address are now also reported.
* The http server no longer redirects <name>.local to an IP address, for better integration with mDNS.
* Add mDNS support, for the extras/mdnsresponder or the LWIP mDNS responder, and enable the LWIP mDNS responder for examples/wificfg.
The mDNS support works here on Linux, both IPv4 and IPv6 if enabled. It might also work on MacOS in Safari but that is not tested and feedback is welcomed? Unfortunately there is no mDNS support on Windows or Android web browsers. For example, a chrome issue to add support https://bugs.chromium.org/p/chromium/issues/detail?id=405925
> wificfg: IPv6 and mDNS support

- examples/ccs811/README.md
- examples/ccs811/ccs811_one_sensor/Makefile
- examples/ccs811/ccs811_one_sensor/ccs811_one_sensor.c
- examples/ccs811/ccs811_plus_sht3x/Makefile
- examples/ccs811/ccs811_plus_sht3x/ccs811_plus_sht3x.c
- examples/ccs811/ccs811_temperature/Makefile
- examples/ccs811/ccs811_temperature/ccs811_temperature.c
- extras/ccs811/README.md
- extras/ccs811/ccs811.c
- extras/ccs811/ccs811.h
- extras/ccs811/component.mk
I have added a driver for the CCS811 indoor air quality sensor. It was tested with the Adafruit CCS811 Air Quality Sensor Breakout. Examples are mostly using only this sensor. But there is also an example where the CCS811 is used together with a SHT3x to determine the ambient temperature for the CCS811 gas measurement.
It would be great if you would merge it to the master :-)
> CCS811 driver added

- open_esplibs/libnet80211/wl_cnx.c
Multicast frames were being dropped by `ieee80211_output_pbuf`. It appears to look up the destination address using `cnx_node_search` which only has an entry for the broadcast address (all ones). This patch modifies `cnx_node_search` to return the broadcast `cnx_node` for the multicast addresses too.
This is needed to support services such as mDNS on the softap interface.
This patch might be a bit of a stretch, perhaps better to patch `ieee80211_output_pbuf`, but there is no source code.
> softap: allow output of multicast frames.

- FreeRTOS/Source/include/stream_buffer.h
- FreeRTOS/Source/include/task.h
- FreeRTOS/Source/tasks.c
svn r2522:
FreeRTOS kernel: Fix extern "C" { in stream_buffer.h.
FreeRTOS kernel: Correct tskKERNEL_VERSION_NUMBER and tskKERNEL_VERSION_MAJOR constants for V10.
Ensure the currently executing task is printed correctly in vTaskList().
> FreeRTOS v10 fixes.

- extras/wificfg/content/wificfg/ap.html
- extras/wificfg/content/wificfg/sta.html
- extras/wificfg/wificfg.c
- extras/wificfg/wificfg.h
- lwip/include/lwipopts.h
The WEP mode does not appear to be implement in the sdk for the AP mode, and defaults to open when WEP is requested which is probably not intended. Remove the WEP option from the wifi config interface.
> wificfg: remove the AP WEP mode option

- open_esplibs/libmain/user_interface.c
Address issues noted in https://github.com/SuperHouse/esp-open-rtos/issues/510
> sdk_system_print_meminfo: fix and correct heap end.

- examples/sht3x/README.md
- examples/sht3x/sht3x.c
- extras/sht3x/README.md
- extras/sht3x/component.mk
- extras/sht3x/sht3x.c
- extras/sht3x/sht3x.h
- extras/sht3x/sht3x_platform.h
1. Minor corrections: 
- Soft reset mechanism of SHT3x does not work when sensor is in any measurement mode. Therefore, a an unsuccessful soft reset it does not abort initialization procedure anymore.
2. Minor changes:
- Automatic delaying and repeating an i2c access when i2c interface is busy was removed. User has to deal with concurrency using semaphores.
- GPIO_ID_PIN macros removed
- typos
3. Changes
- make it possible to use the same driver and example source code also with ESP32 (ESP-IDF)
> SHT3x driver updates

- extras/mdnsresponder/mdnsresponder.c
- extras/mdnsresponder/mdnsresponder.h
* Adds ipv6 support. Compiles with ipv6 enabled and then accepts ipv6 connections and answers AAAA questions.
* Fixes a few overflows of the reply buffer. Reduce the default reply buffer size, name it MDNS_RESPONDER_REPLY_SIZE, and allow overriding.
* Fix mdns_add_TXT.
* Prefer malloc to large stack buffers, to control stack sizes, and try to malloc only the buffer size needed where known in advance.
* Determine the IP addresses when responding, eliminating the update function  and the update task.
* Allow use in StationAP mode too, but bind to the station netif.
* Fix to compile without the debug output.
* Slightly better integration with lwip.
* Some code style changes, not comprehensive.
> mDNS-responder: ipv6 support and fixes

- core/app_main.c
Once scheduling has started, the startup stack is no longer usable, control can never return to that stack. So bump up the heap end in the first task that runs after scheduling has started. This gives back about 1k.
This is a proposal from investigations in https://github.com/SuperHouse/esp-open-rtos/issues/510
A concern is that it is not clear what the top of RAM is used for. It appears to be the start up stack, but might the ROM have stack allocated some memory there that it reuses, or have some other use? Writing to the area and reading back suggests it is not used.
> Reuse the startup stack for the dynamic heap.

- core/app_main.c
- core/newlib_syscalls.c
Some people appear desperate for more dram, and there is 8000 bytes unused. This patch attempts to reclaim that region, to put it onto the malloc free list where is can be used. This is not ideal as it is a fragmented region, but it is dram so faster and more flexible than the 16k+ or iram that might also be added see https://github.com/SuperHouse/esp-open-rtos/issues/510 Some testing and feedback would be welcomed, perhaps also if someone could look over the wdev disassembly and see if they concur about the position and size of this region.
> Reclaim a chunk of unused dram in the wdev bss area, 8000 bytes.

- core/newlib_syscalls.c
The locks are using a bit of the limited ram. It's probably fine to combine some of these to use the same mutex, and this patch does so for the set initialized early. The file locks will still be separate, and dynamically created, so a thread blocking on them will not deadlock all uses of newlib that need a lock. See https://github.com/SuperHouse/esp-open-rtos/issues/510#issuecomment-354001234
> newlib: add an option to combine some locks.

- core/app_main.c
It seems most common for the connection to the wider internet to be via the station netif even if there is also an AP netif, so set the default to the station netif. The lwip ipv4 route logic will still use the AP netif if the destination is to that subnet.
> Change the netif default to the station in STATIONAP mode.

- README.md
FreeRTOS is under MIT license and copyrighted by Amazon
> Update FreeRTOS license.

- extras/sntp/component.mk
- extras/sntp/sntp_fun.c
Primary change is correcting the missing scaling of the microseconds calculation 
Resolves #562 
Other changes address:
* Capture RTC count before any logging
* No "obligatory" printf() logging
* Change logged message to show:
* adjustment about to be made in seconds
* time since last SNTP update
* ratio of the two as ppm
* "cal" value (raw as int, as before)
* Initialize "cal" value from sdk_system_rtc_clock_cali_proc() 
I'm more than happy to squash this, or split into mutiple commits
> Improve extras/sntp -- Issue #562

- common.mk
Every time I update I find that I'm editing common.mk to fix my terminal program. With this PR, I can just stick functions in local.mk (which is in .gitignore) like so:
define will_flash
@echo About to flash, fix terminal program, etc.
endef
define did_flash
@echo Flash finished, clean up.
endef
It might even be possible to determine the exit status of esptool to pass as an argument, but it's not necessary for me.
> Add makefile flash hooks

- common.mk
- parameters.mk
This just pulls out the rboot arguments into a separate variable to allow overriding `RBOOT_ARGS` in local.mk or an application's makefile.
I have several different flash arrangements and rewriting the bootloader with different SPI schemes (DIO, QIO, 4m, 8m, etc) breaks things. Instead of changing `FLASH_SIZE`, `FLASH_MODE`, and `FLASH_SPEED` each time a different chip is flashed, overriding `RBOOT_ARGS` to be blank allows an application to write a custom bootloader (maybe without rboot's config at 0x1000) or none at all.
> Allow overriding bootloader flash arguments

- core/app_main.c
- extras/wificfg/wificfg.c
- lwip/include/arch/cc.h
- lwip/include/arch/sys_arch.h
- lwip/include/lwipopts.h
- lwip/sys_arch.c
- open_esplibs/libmain/user_interface.c
- open_esplibs/libnet80211/ieee80211_hostap.c
- open_esplibs/libnet80211/ieee80211_sta.c
- open_esplibs/libnet80211/wl_cnx.c
- open_esplibs/libwpa/wpa_main.c
* The mdns resolver has been reworked to lower stack and memory usage. It received good feedback from upstream but was unfortunately not accepted as the change uses malloc'ed memory and the upstream lwip wishes to work with pools and without using malloc. The high stack usage was a big problem for esp-open-rtos, so we might have to maintain the differences for now.
* Improved lwip core locking, and lock checking. Upstream improvements, that need some added support from esp-open-rtos specific code. Move core lock is performed when calling from the esp-open-rtos code now, so a little safer. The checking is not enforced, but project might see warning messages and might want to look into them.
* The esp-open-rtos lwip support has been sync'ed with the new freertos port included with lwip. …
> lwip update

- lwip/sys_arch.c
This is not supported on esp-open-rtos, but add a stub to quieten linker warnings.
> lwip add and stub for sys_mbox_trypost_fromisr()

- .gitmodules
- examples/multipwm/Makefile
- examples/multipwm/multipwm_test.c
This is the soft PWM library with the support of independent multiple channels.
As per [Issue 568](https://github.com/SuperHouse/esp-open-rtos/issues/568) I think it makes more sense to add it as a separate library to avoid potential issues with the existing projects where the original single-channel PWM library is being used already.
I added the correspondent example as well.
> Multi-Channel Soft PWM library

- core/newlib_syscalls.c
In trying to save memory had incorrectly shared a non-recursive mutex with recursive mutex uses. Initialize one non-recursive mutex too.
> newlib lock support: use a separate mutex and recursive mutex.

- extras/dhcpserver/dhcpserver.c
Free up all allocated resources on DHCP server stop.
Fixes #589
> extras/dhcpserver - Fix memory leak on stop

- core/include/esp/uart.h
- core/include/esp/uart_regs.h
- examples/uart_config/Makefile
- examples/uart_config/uart_config.c
Some functions and typedefs to customize stopbit count and parity bit type for UART.  
Includes an example about how to use the functions.
(Related Issue: #586 )
> UART: Add ability to configure stopbits and parity bit

- extras/i2c/i2c.c
- extras/i2c/i2c.h
Look-up tables were used for determining the delay loop counts before.
Based on these hand-tuned values, the loop overhead was estimated for
each option -- 80 and 160 MHz, fast and slow GPIO access. Instead of the
great number of tunable parameters one now only has to tune the overhead
values if the code is changed.
Functions were added to the API which allow setting an arbitrary
frequency. API backward compatibility is retained.
> i2c: revise timing calculation

- core/include/esp/uart.h
- core/include/esp/uart_regs.h
This patch to optionally change data bits length of serial bus.
Signed-off-by: Jean-Nicolas Graux <nicogrx@gmail.com>
> uart: add ability to configure byte length

- open_esplibs/libmain/ets_timer.c
If `sdk_ets_timer_arm_ms_us` is called right after `vPortExitCritical` inside `sdk_ets_timer_disarm` on line 247 (by an ISR for example, which was my case), execution will loop forever on line 196, since `timer->next!=ETS_TIMER_NOT_ARMED`, which was supposed to be changed in line 248.
By delaying the IRS or context switch until `sdk_ets_timer_disarm` the problem is fixed.
> bugfix/ets_timer.c: race condition while disarming

- examples/fatfs/main.c
- extras/sdio/sdio.c
The issue was found by using `f_mkdir("directory_name")`.
The function always returned `FR_DISK_ERR` due to an unhandled case in `sdio_write_sectors()`.
According to this documentation: http://www.convict.lu/pdf/ProdManualSDCardv1.9.pdf#page=92 stop transmission command should be sent after writing multiple blocks.
This patch fixes this bug also adds a test case for it.
> Fix for sdio_write_sectors

- open_esplibs/libmain/user_interface.c
Need to flag the dhcp client as stopped, even if the netif is not yet initialized, because the flag is used to control the starting of the dhcpc.
> sdk_wifi_station_dhcpc_stop: ensure the client is flagged as stopped.

- core/sysparam.c
Otherwise when initialization was not successful it may fail with an assertion in FreeRTOS rather than returning SYSPARAM_ERR_NOINIT.
> sysparam: always create the semaphore on init.

- extras/wificfg/wificfg.c
- extras/wificfg/wificfg.h
Remove the wificfg_got_sta_connect() function and replace it with wificfg_wait_until_sta_connected(). This replaces a probe function with a wait function, and this better fits the wifi layer using an event model - the wait function can wait on a station connection event before returning. This helped get this working on the esp-idf framework - small steps in that direction.
The shutdown hooks are called when the wificfg restart function is used. It can be used to implement a cleaner restart, for example blocking further i2c and flash operations.
> wificfg: add shutdown hooks, and add support to wait until connected.

- extras/i2c/i2c.c
- extras/i2c/i2c.h
This also redefines the timeout in FreeRTOS clock ticks, and implements a two stage wait: firstly spinning sampling frequently, and then falling back to a longer wait while sampling less frequently and yielding.
> i2c: increase the default clock strech timeout to 250msec.

- extras/wificfg/wificfg.c
A hostname is also useful in AP mode, so also default it in AP mode - it was previously only defaulted in station mode.
Correct the host redirection logic, to work when no hostname is defined.
> wificfg: default the hostname in all modes.

- core/newlib_syscalls.c
NMI Irq error paths call into printf which will use the newlib locks but these can not be used within the NMI, a task switch can not occur here. This case would be a terminal error path that is attempting to write some debug message in the process, so just bail out of the locking in this case. As a warning a ':' character is emitted and this will typically prefix lines emitted in this context - it would be an error for this path to be take in normal operation.
> newlib: skip locking when within the NMI Irq.

- examples/sysparam_editor/Makefile
- examples/wificfg/Makefile
- open_esplibs/libmain/user_interface.c
Add source code for sdk_wifi_param_save_protect() and a compile time, WIFI_PARAM_SAVE, option to skip writing the wifi state to flash. This avoids wear on the flash and does not appear to be necessary when the app initializes the state anyway.
Define WIFI_PARAM_SAVE to 0 for the wificfg example.
> libmain: add a compile option to avoid saving wifi params to flash

- core/esp_iomux.c
Both maps are in RAM, so there is really no need to allocate extra memory for each entry - no aligned reads.
The assembler for `gpio_to_iomux` and `iomux_to_gpio` differs only in how array entry address (offset) is calculated:
- current: `addx4 a2, a2, a3`
- changed: `add.n a2, a3, a2`
> Shrink gpio<>iomux maps

- core/sysparam.c
As the `addr` is not a pointer adding a size of the `buffer` in words calculates a wrong offset in flash (+8 instead of +32). This eventually leads to the loop overstepping the boundary of the sysparam area and include the beginning of the esp system parameters sector - the last read from 0x003fafe8 to 0x003fb007 with a 4M flash. The latter is not empty, so the sysparam area checker would always see the sysparam area as not empty.
> Fixed sysparams flash area address calculation

- extras/ads111x/ads111x.c
- extras/ads111x/ads111x.h
ADS101x is a faster version of ADS111x ADC, with lower precision.
This change provides basic support for device, by defining sample rates used by ADS101x and providing new ads101x_get_value() function with proper 4-bit shift to obtain actual ADC value.
> Add ADS1015 support to ads111x lib.

- examples/http_get/http_get.c
ipv6.google.com is not available from an IPv4-only network.
httpbin.org gives nice answers to many requests.
> http_get example: Make compatible with IPv4

- extras/dhcpserver/dhcpserver.c
This adds `DHCP_OPTION_LEASE_TIME` to dhcpserver's DHCPOFFER which is required by [rfc2131](https://www.ietf.org/rfc/rfc2131.txt) (table 3, page 28). This fixes the server incompatibility with ISC dhclient (tested on version 4.4.1) which is standard dhcp client on arch.
> added lease time option to dhcpserver's DHCPOFFER

- extras/mactimer/component.mk
- extras/mactimer/mactimer.c
- extras/mactimer/mactimer.h
Support for using the MAC timer, a NMI with a higher priority than the maskable interrupts, but with similar practical code limitations to the MAC layer handler code.
These handlers are very restricted, might be very frustrating to use, but if desperate for better timing then perhaps this might be useful. It also shows how to use the MAC timer.
There is an example coming, a soft uart output driver that helped me driving some sensors.
> mactimer: add MAC NMI timer support.

- examples/tsoftuart/.gitignore
- examples/tsoftuart/FreeRTOSConfig.h
- examples/tsoftuart/Makefile
- examples/tsoftuart/local.mk
- examples/tsoftuart/tsoftuart.c
- extras/mactimer/component.mk
- extras/mactimer/mactimer.c
- extras/mactimer/mactimer.h
- extras/tsoftuart/component.mk
- extras/tsoftuart/tsoftuart.c
- extras/tsoftuart/tsoftuart.h
This has been used to help drive some sensors at 9600 baud with minimal overhead by using a hardware timer, the MAC timer. So far it only implements output, not input. It is also an example of the use of the MAC timer.
There is already a software UART driver, but it has a simpler output implement that spins waiting for delays to pass and it's timing is affected by maskable interrupts.
> tsoftuart: add a softare timer base UART driver, and example.

- extras/http_client_ota/http_buffered_client.c
I was testing HTTP OTA and I realized that OTA locks down when Wifi connection drops. When this happens, POSIX function ```read``` (located at ```HttpClient_download```) returns -1. Since it's implemented as unsigned, ```do { ... } while(read_byte > 0)``` loops forever. Therefore the ```read_byte``` variable must be signed type.
> Http download issue when connection lost

- extras/fonts/tools/create_font.py
- extras/fonts/tools/template.c
Hello. I needed TrueType font support. Unfortunately, the library does not allow the use of TTF font?
I made some updates that made it possible for me ...
However, it has bugs. For larger font sizes, it may be fine, but small font sizes sometimes appear distorted.
I don't know if you would like to catch up .. TTF font support could be useful ..
> Support for TTF font

- extras/pca9685/pca9685.c
It's currently not possible to toggle between full off and full on, as
switching to full on leaves the full off control bit set. The full off
control bit takes precedence according to the datasheet, which means the
signal remains off. (See [datasheet] page 21 for register definitions and
page 24 for information about precedence).
[datasheet]: https://cdn-shop.adafruit.com/datasheets/PCA9685.pdf
The 'normal' branch does correctly clear full off/full on, as it writes
0s to the `LEDn_ON` registers unconditionally and writes 0 to the control
bit in `LEDn_OFF`.
> Fix full on/off in pca9685.
